backend:
  name: git-gateway
  repo: thibaultmalfoy/annebouchara-v2

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Textes"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Extrait", name: "excerpt", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "date"}
      - {label: "Photo de couverture", name: "coverImage", widget: "image"}
      - {label: "Corps", name: "body", widget: "markdown"}